"""drop player_pref_foot column from players

Revision ID: 212e8af61346
Revises: 89a346fe43f8
Create Date: 2026-03-08 11:36:44.308180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212e8af61346'
down_revision = '89a346fe43f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('player_pref_foot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_pref_foot', mysql.ENUM('Left', 'Right', 'Both'), nullable=False))

    # ### end Alembic commands ###
