"""Add scout_photo column

Revision ID: 4d86b29621ac
Revises: 212e8af61346
Create Date: 2026-03-20 11:10:32.668159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d86b29621ac'
down_revision = '212e8af61346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('player_date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('scout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scout_photo', sa.String(length=200), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('video_link',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('video_link',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('scout', schema=None) as batch_op:
        batch_op.drop_column('scout_photo')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('player_date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
