"""empty message

Revision ID: 89a346fe43f8
Revises: 
Create Date: 2026-03-07 15:47:06.080856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a346fe43f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=50), nullable=True),
    sa.Column('admin_email', sa.String(length=150), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=255), nullable=False),
    sa.Column('admin_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_username')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('scout',
    sa.Column('scout_id', sa.Integer(), nullable=False),
    sa.Column('scout_firstname', sa.String(length=100), nullable=False),
    sa.Column('scout_lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('scout_password_hash', sa.String(length=255), nullable=False),
    sa.Column('scout_reg_date', sa.DateTime(), nullable=True),
    sa.Column('scout_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scout_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clubs',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('club_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_firstname', sa.String(length=100), nullable=False),
    sa.Column('player_lastname', sa.String(length=100), nullable=False),
    sa.Column('player_height', sa.Integer(), nullable=True),
    sa.Column('player_pref_foot', sa.Enum('Left', 'Right', 'Both'), nullable=False),
    sa.Column('player_email', sa.String(length=100), nullable=True),
    sa.Column('player_phone', sa.String(length=20), nullable=True),
    sa.Column('player_password_hash', sa.String(length=255), nullable=False),
    sa.Column('player_photo', sa.String(length=200), nullable=True),
    sa.Column('player_date_of_birth', sa.Date(), nullable=True),
    sa.Column('player_created_at', sa.DateTime(), nullable=True),
    sa.Column('player_updated_at', sa.DateTime(), nullable=True),
    sa.Column('primary_position_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['primary_position_id'], ['position.position_id'], ),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('player_email')
    )
    op.create_table('player_positions',
    sa.Column('player_position_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.position_id'], ),
    sa.PrimaryKeyConstraint('player_position_id')
    )
    op.create_table('scout_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('scout_id', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('report_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['scout_id'], ['scout.scout_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(length=200), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('video_created_at', sa.DateTime(), nullable=True),
    sa.Column('video_description', sa.String(length=200), nullable=True),
    sa.Column('video_caption', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('scout_report')
    op.drop_table('player_positions')
    op.drop_table('players')
    op.drop_table('clubs')
    op.drop_table('scout')
    op.drop_table('position')
    op.drop_table('country')
    op.drop_table('admin')
    # ### end Alembic commands ###
